version: '3'
networks:
  db:
  web:
  fila:
services: 
  db: 
    image: postgres:9.6
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      # definir nome diretório backup
      #- ./pg-banco:/var/lib/postgresql/data
    networks:
      - db
  web:
    image: nginx:1.13
    volumes:
      #site
      - ./web:/usr/share/nginx/html
      #proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.7.2
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - db
      - web
      - fila
    depends_on:
      - db
      - fila
  fila:
    image: redis:3.2
    networks:
      - fila
  atendente:
    image: python:3.7.2
    volumes:
      - ./atendente:/atendente
    working_dir: /atendente
    command: bash ./atendente.sh
    networks:
      - fila
    depends_on:
      - fila